# Site settings
title: Scott Emmons
email: scott@scottemmons.com
description: > # this means to ignore newlines until "baseurl:"
  The personal website of Scott Emmons.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://scottemmons.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  scottemmons

# Build settings
markdown: kramdown
